#!/bin/bash

if [[ -z $RUST_DDNS_LOG_FILE ]]; then
RUST_DDNS_LOG_FILE=$HOME/.rust-ddns.log
fi

touch $RUST_DDNS_LOG_FILE

cd $HOME || exit 1

rust-ddns &>> $RUST_DDNS_LOG_FILE

echo "$(tail -n 200 $RUST_DDNS_LOG_FILE)" > $RUST_DDNS_LOG_FILE